In [17]:
a=10
b=20
print(a+b)

30


In [18]:
a=10
b=20
a+b

30

In [19]:
print("Hello world")

Hello world


In [20]:
var1=int(input("Enter a value"))
var1

3

In [2]:
import numpy as np

1D Array

In [3]:
arr1=np.array([1,2,3,4,5])
arr2=arr1+1
print(arr2)
print("array dimension--->",arr1.ndim)
arr1[:]=10
arr1
arr1[2:4]=[20,30]
arr1
arr1.shape

[2 3 4 5 6]
array dimension---> 1


(5,)

2D Array

In [23]:
arr2=np.array([[1,2,3,4],[5,6,3,1],[5,7,8,9],[3,6,4,7]])
arr2.size
arr2.ndim
arr2.dtype
arr2.shape
arr2[2,1]=10
arr2*10
arr2[:,2]
arr2[2,:]=[1,2,3,4]
arr2
arr2[1:3,1:3]=0
arr2



array([[1, 2, 3, 4],
       [5, 0, 0, 1],
       [1, 0, 0, 4],
       [3, 6, 4, 7]])

In [24]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9],[12,43,54],[23,87,56],[3,9,6],[7,9,4]])
arr3
arr3[:,1:3] # to access the second and the third columns 
arr3[:,:2] # to acess the first and second columns
arr3[:,::2] # to access first and third column
arr3
arr3[::6,::2]=-1
arr3[0,0]=-1
arr3[0,2]=-1
arr3[-1,-3]=-1
arr3[-1,-1]=-1
arr3[[0,0,-1,-1],[0,2,-1,-3]]=-2
arr3[[0,1,4],[1,1,1]]
arr3
# access 1,2 and 5th rows abd change the values to 255
arr3[[0,1,4],:]=255 # or arr3[[0,1,4]]
arr3


array([[255, 255, 255],
       [255, 255, 255],
       [  7,   8,   9],
       [ 12,  43,  54],
       [255, 255, 255],
       [  3,   9,   6],
       [ -2,   9,  -2]])

In [25]:
arr3>50# boolean indexing check the arr3 elements if >50.then return true or false
arr3[arr3%2==0] # here only the values which is even is listed


array([ 8, 12, 54,  6, -2, -2])

In [26]:
arr=np.array([12,45,7,19,34,28,90,55,63])
print("all elements greater than 30-->",arr[arr>30])
print("all odd numbers-->",arr[arr%2!=0])
arr[arr%5==0]=-1
print("array after replacing multiples of 5 with -1",arr)
print("No of elements less than 50--->",arr[arr<50].size)

all elements greater than 30--> [45 34 90 55 63]
all odd numbers--> [45  7 19 55 63]
array after replacing multiples of 5 with -1 [12 -1  7 19 34 28 -1 -1 63]
No of elements less than 50---> 8


In [27]:
import numpy as np
arr=np.array([[10,25,40],[55,18,72],[91,30,64]])
print("All numbers greater than 50--->",arr[arr>50])
arr[arr%2==0]=0
print("Array after replacing all even numbers with 0 -->",arr)
print("Sum of all numbers that are divisible by 5--->",sum(arr[arr%5==0]))
y=arr[(arr>20)  & (arr<70)]
print("numbers that are >20 and less than 70--->",y.size)

All numbers greater than 50---> [55 72 91 64]
Array after replacing all even numbers with 0 --> [[ 0 25  0]
 [55  0  0]
 [91  0  0]]
Sum of all numbers that are divisible by 5---> 80
numbers that are >20 and less than 70---> 2


In [28]:
arr=np.array([[12,34,56],[78,90,23],[45,67,89]])
print("Extract elemrnts from 1st and 3rd row--->",arr[::2,])
print("Second column from the array-->",arr[:,1])
print("Specific items 12,90,67 --->",arr[[0,1,2],[0,1,1]])
print("swaped the first and last row--->",arr[::-1])
arr[0,2]=arr[2,0]

Extract elemrnts from 1st and 3rd row---> [[12 34 56]
 [45 67 89]]
Second column from the array--> [34 90 67]
Specific items 12,90,67 ---> [12 90 67]
swaped the first and last row---> [[45 67 89]
 [78 90 23]
 [12 34 56]]


In [29]:
arr=np.array([[5,15,25],[35,45,55],[65,75,85]])
arr1=arr[arr%5==0]
arr1
print("array with multiples of 5 and greater than 30",arr1[arr[arr%5==0]>30])
arr[arr<50]=-1
print("Array after replacing all numbers less than 50 with -1",arr)
arr[:,-1]=100
print(arr)
arr[arr>60]*=2
arr

array with multiples of 5 and greater than 30 [35 45 55 65 75 85]
Array after replacing all numbers less than 50 with -1 [[-1 -1 -1]
 [-1 -1 55]
 [65 75 85]]
[[ -1  -1 100]
 [ -1  -1 100]
 [ 65  75 100]]


array([[ -1,  -1, 200],
       [ -1,  -1, 200],
       [130, 150, 200]])

In [30]:
# SUM
print(arr)
np.sum(arr,axis=0) # axis 0 means columns and axis 1 means row
np.sum(arr,axis=1)
# min
print(np.min(arr))
# max
print(np.max(arr))
# argmax
print(np.argmax(arr)) # index of the max value 
print(np.argmax(arr,axis=0))
print(np.argmax(arr,axis=1))
# argmin
print(np.argmin(arr)) # index of the max values
print(np.argmin(arr,axis=0))
print(np.argmin(arr,axis=1))
# mean
# median
# std
# var


[[ -1  -1 200]
 [ -1  -1 200]
 [130 150 200]]
-1
200
2
[2 2 0]
[2 2 2]
0
[0 0 0]
[0 0 0]


In [31]:
# zero array
np.zeros((5,3))
# ones array
np.ones((5,3))
# full
a=np.full((5,3),7)
# full like
np.full_like(a,5)
# arange
b=np.arange(1,101,1)
#reshape
b.reshape((10,10))
np.reshape(b,(100,))
# random array
np.random.randint(1,1000,(10,5)) # random array
np.random.random((10,5)) # random array with values between 0 and 1 of shape 10,5


array([[0.3386562 , 0.11164269, 0.60211291, 0.44279254, 0.7444549 ],
       [0.59507275, 0.07532943, 0.4957266 , 0.609644  , 0.52856745],
       [0.9797362 , 0.52301617, 0.80382326, 0.75303971, 0.96661117],
       [0.71770568, 0.73136868, 0.47975527, 0.92917248, 0.92118969],
       [0.08227647, 0.42843802, 0.93603953, 0.58412371, 0.89351294],
       [0.57736489, 0.588572  , 0.01889703, 0.86121429, 0.2839959 ],
       [0.95021204, 0.24089094, 0.2349485 , 0.60906426, 0.39312933],
       [0.98273879, 0.04234176, 0.73636696, 0.28573108, 0.70664279],
       [0.05827123, 0.12453278, 0.61631945, 0.02175226, 0.87294864],
       [0.3509913 , 0.21512923, 0.79305538, 0.79183674, 0.29667964]])

In [65]:
arr2d=np.random.randint(1,25,(5,5))
print(arr2d)
print("Third raw",arr2d[2,:])
print("Second column",arr2d[:,1])
print("Submatrix from raw 2 to 4 and column 3 to 5 ",arr2d[1:4,2:5])
print("Transpose array", np.transpose(arr2d))

[[19  8 15 22 24]
 [16 15 16  6 23]
 [ 2  6  8 24 14]
 [11  8 20  3 16]
 [21 13 14 15  7]]
Third raw [ 2  6  8 24 14]
Second column [ 8 15  6  8 13]
Submatrix from raw 2 to 4 and column 3 to 5  [[16  6 23]
 [ 8 24 14]
 [20  3 16]]
Transpose array [[19 16  2 11 21]
 [ 8 15  6  8 13]
 [15 16  8 20 14]
 [22  6 24  3 15]
 [24 23 14 16  7]]


In [57]:
arr1d=np.random.randint(0,50,(20))
print(arr1d)
arrnew=arr1d[arr1d>25]
print("Array with values greaterthan 25--->",arrnew)
arr1d[arr1d<=25]=-1
print("Array with values lessthan 25 repalced to -1 --->",arr1d)

[42 47 30 41  9 48 21 36 29 29  2  8  4  3 42 29 41  8 11 19]
Array with values greaterthan 25---> [42 47 30 41 48 36 29 29 42 29 41]
Array with values lessthan 25 repalced to -1 ---> [42 47 30 41 -1 48 -1 36 29 29 -1 -1 -1 -1 42 29 41 -1 -1 -1]


In [62]:
arr=np.arange(1,17)
print(arr)
arr2d=arr.reshape((4,4))
print(arr2d)
print("Transpose matrix",np.transpose(arr2d))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose matrix [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [67]:
arr2d=np.random.randint(0,100,(10,4))
print(arr2d)
print("sum of all elements--->",np.sum(arr2d))
print("mean of entire array--->",np.mean(arr2d))
print("Max value in each column-->",np.max(arr2d,axis=0))
print("Min value in each row-->",np.min(arr2d,axis=1))

[[ 9 76 15 92]
 [88 60 66 57]
 [12 38 91 35]
 [73 56 37 82]
 [37 61  7 18]
 [94 35 50 65]
 [ 0 58 29 83]
 [31 35 15 76]
 [53 24 28 55]
 [23 81 73 65]]
sum of all elements---> 1983
mean of entire array---> 49.575
Max value in each column--> [94 81 91 92]
Min value in each row--> [ 9 57 12 37  7 35  0 15 24 23]


In [84]:
arr2d=np.reshape(np.arange(1,37),(6,6))
print(arr2d)
print(arr2d[[2,4,5],[3,5,0]])
print("Element at (2,3)--->",arr2d[2,3])
print("Element at (4,5)--->",arr2d[4,5])
print("Element at (5,0)--->",arr2d[5,0])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[16 30 31]
Element at (2,3)---> 16
Element at (4,5)---> 30
Element at (5,0)---> 31


In [81]:
arr2d=np.reshape(np.arange(1,26),(5,5))
print(arr2d)
arr=arr2d[[4,2,0,3,1],:]
print(arr)
arr=arr[:,[1,3,0,4,2]]
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[21 22 23 24 25]
 [11 12 13 14 15]
 [ 1  2  3  4  5]
 [16 17 18 19 20]
 [ 6  7  8  9 10]]
[[22 24 21 25 23]
 [12 14 11 15 13]
 [ 2  4  1  5  3]
 [17 19 16 20 18]
 [ 7  9  6 10  8]]


In [92]:
a=np.array((1,2,3,4))
b=np.array((2,4,2,4))
np.dot(a,b)

np.int64(32)

In [6]:
arr3d=np.array([[[1,2,3],[10,11,12]],[[1,2,3],[3,4,5]]])
arr3d.shape # first 2 is the height(no of 2d arrays),next 2,3 is the raws and columns of each 2d array.
arr3d[1,1,1]

np.int64(4)

In [35]:
arr3d2=np.random.randint(1,100,(2,3,4))
arr3d2
arr3d3=np.reshape(arr3d2,(3,2,4))
print(arr3d3)
print("1d array-->",arr3d3.flatten())
arr3d3[1][arr3d3[1]%2==0]=-1
print("repalce all even values in 2nd depth with -1",arr3d3)

print("check array contains a number greater than 95 or not-->",np.any(arr3d2[arr3d2>95]))
arr3d3[0,:,3]=10
print("array with 4 column 3--->",arr3d3)

[[[81 69 80 65]
  [ 4 40 26 19]]

 [[80 49 81 20]
  [39 70 64 35]]

 [[50 17 56 33]
  [72 25 74 94]]]
1d array--> [81 69 80 65  4 40 26 19 80 49 81 20 39 70 64 35 50 17 56 33 72 25 74 94]
repalce all even values in 2nd depth with -1 [[[81 69 80 65]
  [ 4 40 26 19]]

 [[-1 49 81 -1]
  [39 -1 -1 35]]

 [[50 17 56 33]
  [72 25 74 94]]]
check array contains a number greater than 95 or not--> False
array with 4 column 3---> [[[81 69 80 10]
  [ 4 40 26 10]]

 [[-1 49 81 -1]
  [39 -1 -1 35]]

 [[50 17 56 33]
  [72 25 74 94]]]


In [12]:
arr3d1=np.array([[[1,2,3,4],[1,4,5,6],[1,5,6,7]],[[2,3,4,5],[2,4,5,6],[2,5,6,7]],
                [[10,11,12,13],[10,12,13,14],[10,13,14,15]],[[11,12,13,14],[12,13,14,15],[10,11,15,16]]])
print(arr3d1)
print(arr3d1.ndim)
print(arr3d1.shape)
print(arr3d1[2,1,0])

[[[ 1  2  3  4]
  [ 1  4  5  6]
  [ 1  5  6  7]]

 [[ 2  3  4  5]
  [ 2  4  5  6]
  [ 2  5  6  7]]

 [[10 11 12 13]
  [10 12 13 14]
  [10 13 14 15]]

 [[11 12 13 14]
  [12 13 14 15]
  [10 11 15 16]]]
3
(4, 3, 4)
10
